<a href="https://colab.research.google.com/github/bravi29/NumPy-Exercises/blob/master/01_NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

![[github link](https://github.com/bravi29)](./images/NumPy.png) [Github link](https://github.com/bravi29)
___



# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!


**Numpy | ndarray**       |      **N-Dimensional array(ndarray) in Numpy**
      

Array in Numpy is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In Numpy, number of dimensions of the array is called rank of the array.A tuple of integers giving the size of the array along each dimension is known as shape of the array. An array class in Numpy is called as ndarray. Elements in Numpy arrays are accessed by using square brackets and can be initialized by using nested Python Lists.

       

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [0]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [14]:
my_list = [1,2,3]  # This is simple list in Python
my_list

[1, 2, 3]

In [16]:
np.array(my_list) # Here np.array() is the function we are using for convert a list to array 

array([1, 2, 3])

In [17]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]] # Here we are declaring list of list 
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [38]:
# Creating array from list with type float
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print ("Array created using passed list:\n", a)

Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]


In [39]:
# Creating array from tuple
b = np.array((1 , 3, 2))
print ("\nArray created using passed tuple:\n", b)


Array created using passed tuple:
 [1 3 2]


In [40]:
# Creating a 3X4 array with all zeros
c = np.zeros((3, 4))
print ("\nAn array initialized with all zeros:\n", c)


An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [41]:
# Create a constant value array of complex type
d = np.full((3, 3), 6, dtype = 'complex')
print ("\nAn array initialized with all 6s. Array type is complex:\n", d)


An array initialized with all 6s. Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [0]:
arr = np.array( [[ 1, 2, 3],[ 4, 2, 5]] )  # Creating array object

In [37]:
print("Array is of type: ", type(arr))    # Printing type of arr object

Array is of type:  <class 'numpy.ndarray'>


In [31]:
print("No. of dimensions: ", arr.ndim)  # Printing array dimensions (axes)

No. of dimensions:  2


In [32]:
print("Shape of array: ", arr.shape)  # Printing shape of array

Shape of array:  (2, 3)


In [33]:
print("Size of array: ", arr.size)  # Printing size (total number of elements) of array

Size of array:  6


In [34]:
print("Array stores elements of type: ", arr.dtype)   # Printing type of elements in array

Array stores elements of type:  int64


In [19]:
np.array(my_matrix) # Converting list of list to np array using np.array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [20]:
np.arange(0,10)             # This method returns 10 numbers of array start from 0 and end with 9 and exclude 10 
                            # Here 0 is start value and 10 is End value 


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(0,11,2)           # This function also same as above but here we are passing the third parameter 2 that is called step size
                            # As we given step size 2 it returns 2 evenly spaced values between 0 to 11

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

**Zeros**

numpy.zeros(shape, dtype=float, order='C')

Return a new array of given shape and type, filled with zeros.

**Parameters:**

**shape :** int or tuple of ints

Shape of the new array, e.g., (2, 3) or 2.

**dtype :** data-type, optional

The desired data-type for the array, e.g., numpy.int8. Default is numpy.float64.

**order :** bold text{‘C’, ‘F’}, optional, default: ‘C’

Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory.

**Returns:**	
**out :** ndarray
Array of zeros with the given shape, dtype, and order.

In [24]:
np.zeros(3)                 # This will generate array of 3 zero values

array([0., 0., 0.])

In [26]:
np.zeros((5,5))             # This will generate 5 rows and 5 columns of zero values array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.zeros((5,), dtype=int)  # If you see the above result values are 0. that means by default data-taype is numpy.float64
                           # We want integer type we have to specify the dtype = int
                           # The desired data-type for the array, e.g., numpy.int8. Default is numpy.float64.

array([0, 0, 0, 0, 0])

In [10]:
np.zeros((2, 1))           # This will give us array of 2 rows and 1 column

array([[0.],
       [0.]])

In [11]:
s = (2,2)
np.zeros(s)

array([[0., 0.],
       [0., 0.]])

In [12]:
np.zeros(s,dtype=int)

array([[0, 0],
       [0, 0]])

### Ones

numpy.ones(shape, dtype=None, order='C')

Return a new array of given shape and type, filled with ones.

**Parameters:**	

shape : int or sequence of ints

Shape of the new array, e.g., (2, 3) or 2.

**dtype :** data-type, optional

The desired data-type for the array, e.g., numpy.int8. Default is numpy.float64.

**order :** {‘C’, ‘F’}, optional, default: C

Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory.

**Returns:	**

**out :** ndarray

Array of ones with the given shape, dtype, and order.

In [27]:
np.ones(3)                  # This will generate array of 3 ones values

array([1., 1., 1.])

In [28]:
np.ones((3,3))              # This will generate 3 rows and 3 columns of zero values array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
 np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
 np.ones((5,), dtype=int)

array([1, 1, 1, 1, 1])

In [15]:
np.ones((2, 1))

array([[1.],
       [1.]])

In [19]:
s = (2,2)
np.ones(s,dtype=int)

array([[1, 1],
       [1, 1]])

In [21]:
np.ones(0)   # Empty array

array([], dtype=float64)

### linspace
**numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)**

Return evenly spaced numbers over a specified interval.

Returns num evenly spaced samples, calculated over the interval [start, stop].

The endpoint of the interval can optionally be excluded.

**Parameters:**	

**start** : array_like

The starting value of the sequence.

**stop** : array_like

The end value of the sequence, unless endpoint is set to False. In that case, the sequence consists of all but the last of num + 1 evenly spaced samples, so that stop is excluded. Note that the step size changes when endpoint is False.

**num** : int, optional

Number of samples to generate. Default is 50. Must be non-negative.

**endpoint** : bool, optional

If True, stop is the last sample. Otherwise, it is not included. Default is True.

**retstep** : bool, optional

If True, return (samples, step), where step is the spacing between samples.

**dtype** : dtype, optional

The type of the output array. If dtype is not given, infer the data type from the other input arguments.

New in version 1.9.0.

**axis :** int, optional

The axis in the result to store the samples. Relevant only if start or stop are array-like. By default (0), the samples will be along a new axis inserted at the beginning. Use -1 to get an axis at the end.

New in version 1.16.0.

**Returns:**	

**samples :** ndarray

There are num equally spaced samples in the closed interval [start, stop] or the half-open interval [start, stop) (depending on whether endpoint is True or False).

**step :** float, optional

Only returned if retstep is True

Size of spacing between samples.

In [32]:
np.linspace(0,10,3)   # This returns 3 evenly spaced numbers between 0 to 10

array([ 0.,  5., 10.])

In [34]:
np.linspace(0,10,-1)  # This will give us error because num - Number of samples must be non-negative value
                      # we can see ValueError: Number of samples, -1, must be non-negative. 

ValueError: ignored

In [35]:
np.linspace(0,10,50)   # This returns 50 evenly spaced numbers from 0 to 10

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [37]:
np.linspace(2.0, 3.0, num=5)   # This returns 5 evenly spaced numbers from 2.0 to 3.0

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [41]:
np.linspace(2.0, 3.0, num=5, endpoint=False)  # endpoint tell us whether stop value include or not
                                              # By Default endpoint is true this will include stop value
                                              # If True, stop is the last sample. Otherwise, it is not included. Default is True.

array([2. , 2.2, 2.4, 2.6, 2.8])

In [43]:
np.linspace(2.0, 3.0, num=5, endpoint=False, retstep=True)  # If retstep=True then result is tuple of sample array and step size
                                                            # If True, return (samples, step), where step is the spacing between samples.

(array([2. , 2.2, 2.4, 2.6, 2.8]), 0.2)

## eye

Creates an identity matrix

**numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')**

Return a 2-D array with ones on the diagonal and zeros elsewhere.

**Parameters:**

**N :** int

Number of rows in the output.

**M :** int, optional

Number of columns in the output. If None, defaults to N.

**k :** int, optional

Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.

**dtype :** data-type, optional
Data-type of the returned array.

**order :** {‘C’, ‘F’}, optional
Whether the output should be stored in row-major (C-style) or column-major (Fortran-style) order in memory.

New in version 1.14.0.

**Returns:**	
I : ndarray of shape (N,M)
An array where all elements are equal to zero, except for the k-th diagonal, whose values are equal to one.


In [0]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [22]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [25]:
np.eye(3, k=1)   # Here Index of the diagonal start from 1 d
                    # defalut 0

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [26]:
np.eye(3, k=1, dtype=int)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [27]:
np.eye(1)

array([[1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [0]:
np.random.rand(2)

array([ 0.11570539,  0.35279769])

In [0]:
np.random.rand(5,5)

array([[ 0.66660768,  0.87589888,  0.12421056,  0.65074126,  0.60260888],
       [ 0.70027668,  0.85572434,  0.8464595 ,  0.2735416 ,  0.10955384],
       [ 0.0670566 ,  0.83267738,  0.9082729 ,  0.58249129,  0.12305748],
       [ 0.27948423,  0.66422017,  0.95639833,  0.34238788,  0.9578872 ],
       [ 0.72155386,  0.3035422 ,  0.85249683,  0.30414307,  0.79718816]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [0]:
np.random.randn(2)

array([-0.27954018,  0.90078368])

In [0]:
np.random.randn(5,5)

array([[ 0.70154515,  0.22441999,  1.33563186,  0.82872577, -0.28247509],
       [ 0.64489788,  0.61815094, -0.81693168, -0.30102424, -0.29030574],
       [ 0.8695976 ,  0.413755  ,  2.20047208,  0.17955692, -0.82159344],
       [ 0.59264235,  1.29869894, -1.18870241,  0.11590888, -0.09181687],
       [-0.96924265, -1.62888685, -2.05787102, -0.29705576,  0.68915542]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [0]:
np.random.randint(1,100)

44

In [0]:
np.random.randint(1,100,10)

array([13, 64, 27, 63, 46, 68, 92, 10, 58, 24])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [0]:
arrre = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [46]:
arrre

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [47]:
ranarr

array([35, 39, 28,  9, 26, 42, 16, 33, 29, 40])

## Reshape
Returns an array containing the same data with a new shape.

We can use reshape method to reshape an array. Consider an array with shape (a1, a2, a3, …, aN). We can reshape and convert it into another array with shape (b1, b2, b3, …, bM). The only required condition is:
a1 x a2 x a3 … x aN = b1 x b2 x b3 … x bM . (i.e original size of array remains unchanged.)

In [48]:
arrre.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
arrre

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [50]:
ranarr

array([35, 39, 28,  9, 26, 42, 16, 33, 29, 40])

In [51]:
ranarr.max()

42

In [52]:
ranarr.argmax()

5

In [53]:
ranarr.min()

9

In [54]:
ranarr.argmin()

3

## Shape

Shape is an attribute that arrays have (not a method):

In [55]:
# Vector
arr.shape

(2, 3)

In [57]:
# Notice the two sets of brackets
arrre.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [59]:
arrre.reshape(1,25).shape

(1, 25)

In [60]:
arrre.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [61]:
arrre.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [62]:
arr.dtype

dtype('int64')

# Good Luck

**Whish you happy learning**